version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3308:3306"  # Puerto MySQL expuesto en 3308
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql

    networks:
      - hotelbediax-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "2023:2023"
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql-db
    networks:
      - hotelbediax-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Puerto por defecto de Vite
    networks:
      - hotelbediax-network

networks:
  hotelbediax-network:
    driver: bridge
